# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell commands. You could use `make` as well.
cmd = "go build -buildvcs=false -o ./tmp/server ."
# Binary file yields from `cmd`.
bin = "tmp/server"
# Customize binary.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/server server"