# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/consumer ."
# Binary file yields from `cmd`.
bin = "tmp/consumer"
# Customize binary.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/consumer consumer"