version: "3.9"

services:
  ecooda:
    build:
      context: .
      dockerfile: Dockerfile
      target: air-server
      secrets:
        - netrc
    volumes:
      - .:/go/src/github.com/ruifrodrigues/ecooda
    working_dir: /go/src/github.com/ruifrodrigues/ecooda
    networks:
      - default
    ports:
      - "80:80"

volumes:
  ecooda-data:

secrets:
  netrc:
    file: .netrc
