version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: air-server
      secrets:
        - netrc
    volumes:
      - .:/go/src/github.com/ruifrodrigues/ecooda
    working_dir: /go/src/github.com/ruifrodrigues/ecooda
    networks:
      - default
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50051:50051"

  mysql-db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  backend-data:
  mysql-db-data:

secrets:
  netrc:
    file: .netrc
