# curl --location --request POST 'http://ecooda.local:8080/challenges/36bb6b4f-cf0d-419a-8150-2722ecbd463a/remove-category'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "categoryUuid": "b1969042-ea0a-4fb6-8780-1d1bc6e0bc37"
#}'
POST http://ecooda.local:8080/challenges/36bb6b4f-cf0d-419a-8150-2722ecbd463a/remove-category
Content-Type: application/json

{
  "categoryUuid": "b1969042-ea0a-4fb6-8780-1d1bc6e0bc37"
}

###

