CREATE TABLE IF NOT EXISTS categories
(
    id         INTEGER      NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
    uuid       VARCHAR(32)  NOT NULL UNIQUE,
    name       VARCHAR(128) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP    NULL
);
