// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: cursor/v1/cursor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Previous int32 `protobuf:"varint,1,opt,name=previous,proto3" json:"previous,omitempty"`
	Current  int32 `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Next     int32 `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	Count    int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cursor_v1_cursor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_v1_cursor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_cursor_v1_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *Cursor) GetPrevious() int32 {
	if x != nil {
		return x.Previous
	}
	return 0
}

func (x *Cursor) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Cursor) GetNext() int32 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *Cursor) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_cursor_v1_cursor_proto protoreflect.FileDescriptor

var file_cursor_v1_cursor_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x68, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x95, 0x01,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x42,
	0x0b, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x69, 0x66, 0x72,
	0x6f, 0x64, 0x72, 0x69, 0x67, 0x75, 0x65, 0x73, 0x2f, 0x65, 0x63, 0x6f, 0x6f, 0x64, 0x61, 0x2f,
	0x73, 0x74, 0x75, 0x62, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2f,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x15, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cursor_v1_cursor_proto_rawDescOnce sync.Once
	file_cursor_v1_cursor_proto_rawDescData = file_cursor_v1_cursor_proto_rawDesc
)

func file_cursor_v1_cursor_proto_rawDescGZIP() []byte {
	file_cursor_v1_cursor_proto_rawDescOnce.Do(func() {
		file_cursor_v1_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(file_cursor_v1_cursor_proto_rawDescData)
	})
	return file_cursor_v1_cursor_proto_rawDescData
}

var file_cursor_v1_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cursor_v1_cursor_proto_goTypes = []interface{}{
	(*Cursor)(nil), // 0: cursor.v1.Cursor
}
var file_cursor_v1_cursor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cursor_v1_cursor_proto_init() }
func file_cursor_v1_cursor_proto_init() {
	if File_cursor_v1_cursor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cursor_v1_cursor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cursor_v1_cursor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_v1_cursor_proto_goTypes,
		DependencyIndexes: file_cursor_v1_cursor_proto_depIdxs,
		MessageInfos:      file_cursor_v1_cursor_proto_msgTypes,
	}.Build()
	File_cursor_v1_cursor_proto = out.File
	file_cursor_v1_cursor_proto_rawDesc = nil
	file_cursor_v1_cursor_proto_goTypes = nil
	file_cursor_v1_cursor_proto_depIdxs = nil
}
